language: python
python: 3.6
env:
  global:
  - PKG_NAME=pickle_blosc
  - CIBW_SKIP="cp27-* cp34-* cp35-*"
  - CIBW_BEFORE_BUILD_LINUX=ci/before-build-linux
  - CIBW_BEFORE_BUILD_MACOS=ci/before-build-macos
  - CIBW_ENVIRONMENT_LINUX="BLOSC_DIR=/usr/local/"
  - CIBW_TEST_COMMAND="python -c \"import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())\""
matrix:
  include:
  - sudo: required
    services:
    - docker
  - os: osx
    language: generic
    before_install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew unlink python2
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3 zlib
    - export PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH
    - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
    - ln -s $(brew --prefix)/bin/python3 $(brew --prefix)/bin/python
    - ln -s $(brew --prefix)/bin/pip3 $(brew --prefix)/bin/pip
    - hash -r
    - python -m pip install --upgrade pip setuptools wheel
addons:
  apt:
    packages:
    - libffi-dev
    - libffi6
    - cmake
script:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    sudo mkdir -p /usr/local/man
    sudo chown -R "${USER}:admin" /usr/local/man
  fi
- |
  if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    # Compile and install blosc
    curl -L -O https://github.com/Blosc/c-blosc/archive/v1.16.3.tar.gz
    tar xzf v1.16.3.tar.gz
    pushd c-blosc-1.16.3
    mkdir build
    cd build
    cmake ..
    cmake --build . --target install
    ldconfig
    popd
  fi
- git clean -xdf
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
- python -m pip install cibuildwheel>=0.10.0
- cibuildwheel --output-dir wheelhouse
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    python -m pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: AxKpJCHJi8gGfpziWkuon96DOJYH8hgBPdreAXczPrFkIXVruvbXmZCOn1kcFWFnJ5CNWbl5xrKQO96Eaigrscfk6ib9STGmQTqT9lxKa/P88098nTARBPEfatRvwq12QNR73Ng7WXXkJf1vzhDUnvgDqOqtNVeB98v1aJlvnPIcL3Gw3s6ojSFJLvC0sb3DM6tnaHme/yyE1S8RjTDPAxrEn08qIaOmhApblnf0SRxHrJyMp9IAAmDMvbF5oYFrL+FfBbkE7x4vk+KwuDxhntyoNPTzq+STKSU/aHSvwzBPG6d/erYgw9lBUBLhHiTH4DI7LnCMReFK0VRp1R+CEuybQHi3TK/BXm2ebHkKc0n5HjYYPkIJKleD5X4m35a+UvW+kf9kTJBrUOa01wB1Zaqh9Cuktr/lmZzv6F5hCAJXP7OtUBhBs/X0dh5xRWOmoXjU4YE9UbqfYafk4BtwbM3+tSaoLwoZow1SrsEabLAj/tYq19cuyyclsbSihqnutX2bJcTXMqZ2v6T6DRLoW0fKESXg91aGLh5FqYvQcclLXuRRb9G2kpcvdJVWlbwvF828uRASRDaDcN6lBfLaAf10p1LEMFFb69at6XLXjVX22QM7RbBy9WRarV/of0EXklBTn/QQlfSCCUC9y2FnIkN8jJb0ToXeD5lIinhfIIw=
  on:
    tags: true
    repo: limix/pickle-blosc
    banch: master
    python: 3.6
